# IOTA Devnet Network Configuration
network: devnet
platform: iota
rpc:
  url: https://api.devnet.iota.cafe
  timeout: 60000
deployment:
  gasBudget: 50000000
  confirmationTimeout: 60
  wallet:
    mnemonicId: devnet-deployer-mnemonic
    addressIndex: 0