# IOTA Testnet Network Configuration
network: testnet
platform: iota
rpc:
  url: https://api.testnet.iota.cafe
  timeout: 60000
deployment:
  gasBudget: 50000000
  confirmationTimeout: 60
  wallet:
    mnemonicId: deployer-mnemonic
    addressIndex: 0