# IOTA Mainnet Network Configuration
network: mainnet
platform: iota
rpc:
  url: https://api.mainnet.iota.cafe
  timeout: 60000
deployment:
  gasBudget: 100000000
  confirmationTimeout: 120
  wallet:
    mnemonicId: mainnet-deployer-mnemonic
    addressIndex: 0