# IOTA Devnet Network Configuration
network: devnet
platform: iota
rpc:
  url: https://api.devnet.iota.cafe
  timeout: 60000
deployment:
  gasBudget: 50000000
  confirmationTimeout: 60
  wallet:
    mnemonicId: devnet-deployer-mnemonic
    addressIndex: 0
  gasStation:
    url: https://gas-station.devnet.iota.cafe
    authToken: ${DEVNET_GAS_STATION_AUTH}
contracts:
  nft:
    moduleName: nft
    dependencies: ["0x1", "0x2"]
    packageController:
      addressIndex: 0 