name: Build, Lint, Test, Docs Next

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  dist:
    runs-on: ubuntu-latest

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Download IOTA CLI
        run: |
          cd ..
          wget https://github.com/iotaledger/iota/releases/download/v0.9.0-alpha/iota-v0.9.0-alpha-linux-x86_64.tgz -O iota-cli.tgz
          tar xzf iota-cli.tgz
          chmod +x iota
          sudo mv iota /usr/local/bin/iota
          iota --version

      - name: Download SUI CLI
        run: |
          cd ..
          wget https://github.com/MystenLabs/sui/releases/download/testnet-v1.40.3/sui-testnet-v1.40.3-ubuntu-x86_64.tgz -O sui-cli.tgz
          tar xzf sui-cli.tgz
          chmod +x sui
          sudo mv sui /usr/local/bin/sui
          sui --version

      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
